services:
  frontend:
    build:
      context: frontend
      target: development
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - /project/node_modules
    expose:
      - 3306
      - 33060

  backend:
    build: ./backend
    container_name: backend
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"    

  proxy:
    container_name: proxy
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - frontend